/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as HomeRouteImport } from './routes/home.tsx'
import { Route as LoginCallbackRouteImport } from './routes/login/callback.tsx'
import { Route as authSignupRouteImport } from './routes/(auth)/signup.tsx'
import { Route as authLoginRouteImport } from './routes/(auth)/login.tsx'
import { Route as appAboutRouteImport } from './routes/(app)/about.tsx'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout.tsx'
import { Route as appNgoProfileRouteImport } from './routes/(app)/ngo/profile.tsx'
import { Route as appNgoHistoryRouteImport } from './routes/(app)/ngo/history.tsx'
import { Route as appNgoDashboardRouteImport } from './routes/(app)/ngo/dashboard.tsx'
import { Route as appDonorProfileRouteImport } from './routes/(app)/donor/profile.tsx'
import { Route as appDonorHistoryRouteImport } from './routes/(app)/donor/history.tsx'
import { Route as appDonorDashboardRouteImport } from './routes/(app)/donor/dashboard.tsx'
import { Route as appDonationsIdRouteImport } from './routes/(app)/donations/$id.tsx'
import { Route as appDonorDonationsIndexRouteImport } from './routes/(app)/donor/donations/index.tsx'
import { Route as appNgoDonationsBrowseRouteImport } from './routes/(app)/ngo/donations/browse.tsx'
import { Route as appNgoDonationsAcceptedRouteImport } from './routes/(app)/ngo/donations/accepted.tsx'
import { Route as appDonorDonationsCreateRouteImport } from './routes/(app)/donor/donations/create.tsx'
import { Route as appDonorDonationsDonationIdEditRouteImport } from './routes/(app)/donor/donations/$donationId/edit.tsx'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/(app)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appNgoProfileRoute = appNgoProfileRouteImport.update({
  id: '/(app)/ngo/profile',
  path: '/ngo/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appNgoHistoryRoute = appNgoHistoryRouteImport.update({
  id: '/(app)/ngo/history',
  path: '/ngo/history',
  getParentRoute: () => rootRouteImport,
} as any)
const appNgoDashboardRoute = appNgoDashboardRouteImport.update({
  id: '/(app)/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorProfileRoute = appDonorProfileRouteImport.update({
  id: '/(app)/donor/profile',
  path: '/donor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorHistoryRoute = appDonorHistoryRouteImport.update({
  id: '/(app)/donor/history',
  path: '/donor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorDashboardRoute = appDonorDashboardRouteImport.update({
  id: '/(app)/donor/dashboard',
  path: '/donor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonationsIdRoute = appDonationsIdRouteImport.update({
  id: '/(app)/donations/$id',
  path: '/donations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorDonationsIndexRoute = appDonorDonationsIndexRouteImport.update({
  id: '/(app)/donor/donations/',
  path: '/donor/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const appNgoDonationsBrowseRoute = appNgoDonationsBrowseRouteImport.update({
  id: '/(app)/ngo/donations/browse',
  path: '/ngo/donations/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const appNgoDonationsAcceptedRoute = appNgoDonationsAcceptedRouteImport.update({
  id: '/(app)/ngo/donations/accepted',
  path: '/ngo/donations/accepted',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorDonationsCreateRoute = appDonorDonationsCreateRouteImport.update({
  id: '/(app)/donor/donations/create',
  path: '/donor/donations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const appDonorDonationsDonationIdEditRoute =
  appDonorDonationsDonationIdEditRouteImport.update({
    id: '/(app)/donor/donations/$donationId/edit',
    path: '/donor/donations/$donationId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/donations/$id': typeof appDonationsIdRoute
  '/donor/dashboard': typeof appDonorDashboardRoute
  '/donor/history': typeof appDonorHistoryRoute
  '/donor/profile': typeof appDonorProfileRoute
  '/ngo/dashboard': typeof appNgoDashboardRoute
  '/ngo/history': typeof appNgoHistoryRoute
  '/ngo/profile': typeof appNgoProfileRoute
  '/donor/donations/create': typeof appDonorDonationsCreateRoute
  '/ngo/donations/accepted': typeof appNgoDonationsAcceptedRoute
  '/ngo/donations/browse': typeof appNgoDonationsBrowseRoute
  '/donor/donations/': typeof appDonorDonationsIndexRoute
  '/donor/donations/$donationId/edit': typeof appDonorDonationsDonationIdEditRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/donations/$id': typeof appDonationsIdRoute
  '/donor/dashboard': typeof appDonorDashboardRoute
  '/donor/history': typeof appDonorHistoryRoute
  '/donor/profile': typeof appDonorProfileRoute
  '/ngo/dashboard': typeof appNgoDashboardRoute
  '/ngo/history': typeof appNgoHistoryRoute
  '/ngo/profile': typeof appNgoProfileRoute
  '/donor/donations/create': typeof appDonorDonationsCreateRoute
  '/ngo/donations/accepted': typeof appNgoDonationsAcceptedRoute
  '/ngo/donations/browse': typeof appNgoDonationsBrowseRoute
  '/donor/donations': typeof appDonorDonationsIndexRoute
  '/donor/donations/$donationId/edit': typeof appDonorDonationsDonationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/(app)/_layout': typeof appLayoutRoute
  '/(app)/about': typeof appAboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/login/callback': typeof LoginCallbackRoute
  '/(app)/donations/$id': typeof appDonationsIdRoute
  '/(app)/donor/dashboard': typeof appDonorDashboardRoute
  '/(app)/donor/history': typeof appDonorHistoryRoute
  '/(app)/donor/profile': typeof appDonorProfileRoute
  '/(app)/ngo/dashboard': typeof appNgoDashboardRoute
  '/(app)/ngo/history': typeof appNgoHistoryRoute
  '/(app)/ngo/profile': typeof appNgoProfileRoute
  '/(app)/donor/donations/create': typeof appDonorDonationsCreateRoute
  '/(app)/ngo/donations/accepted': typeof appNgoDonationsAcceptedRoute
  '/(app)/ngo/donations/browse': typeof appNgoDonationsBrowseRoute
  '/(app)/donor/donations/': typeof appDonorDonationsIndexRoute
  '/(app)/donor/donations/$donationId/edit': typeof appDonorDonationsDonationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/about'
    | '/login'
    | '/signup'
    | '/login/callback'
    | '/donations/$id'
    | '/donor/dashboard'
    | '/donor/history'
    | '/donor/profile'
    | '/ngo/dashboard'
    | '/ngo/history'
    | '/ngo/profile'
    | '/donor/donations/create'
    | '/ngo/donations/accepted'
    | '/ngo/donations/browse'
    | '/donor/donations/'
    | '/donor/donations/$donationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/about'
    | '/login'
    | '/signup'
    | '/login/callback'
    | '/donations/$id'
    | '/donor/dashboard'
    | '/donor/history'
    | '/donor/profile'
    | '/ngo/dashboard'
    | '/ngo/history'
    | '/ngo/profile'
    | '/donor/donations/create'
    | '/ngo/donations/accepted'
    | '/ngo/donations/browse'
    | '/donor/donations'
    | '/donor/donations/$donationId/edit'
  id:
    | '__root__'
    | '/home'
    | '/(app)/_layout'
    | '/(app)/about'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/login/callback'
    | '/(app)/donations/$id'
    | '/(app)/donor/dashboard'
    | '/(app)/donor/history'
    | '/(app)/donor/profile'
    | '/(app)/ngo/dashboard'
    | '/(app)/ngo/history'
    | '/(app)/ngo/profile'
    | '/(app)/donor/donations/create'
    | '/(app)/ngo/donations/accepted'
    | '/(app)/ngo/donations/browse'
    | '/(app)/donor/donations/'
    | '/(app)/donor/donations/$donationId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  appLayoutRoute: typeof appLayoutRoute
  appAboutRoute: typeof appAboutRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  appDonationsIdRoute: typeof appDonationsIdRoute
  appDonorDashboardRoute: typeof appDonorDashboardRoute
  appDonorHistoryRoute: typeof appDonorHistoryRoute
  appDonorProfileRoute: typeof appDonorProfileRoute
  appNgoDashboardRoute: typeof appNgoDashboardRoute
  appNgoHistoryRoute: typeof appNgoHistoryRoute
  appNgoProfileRoute: typeof appNgoProfileRoute
  appDonorDonationsCreateRoute: typeof appDonorDonationsCreateRoute
  appNgoDonationsAcceptedRoute: typeof appNgoDonationsAcceptedRoute
  appNgoDonationsBrowseRoute: typeof appNgoDonationsBrowseRoute
  appDonorDonationsIndexRoute: typeof appDonorDonationsIndexRoute
  appDonorDonationsDonationIdEditRoute: typeof appDonorDonationsDonationIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/ngo/profile': {
      id: '/(app)/ngo/profile'
      path: '/ngo/profile'
      fullPath: '/ngo/profile'
      preLoaderRoute: typeof appNgoProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/ngo/history': {
      id: '/(app)/ngo/history'
      path: '/ngo/history'
      fullPath: '/ngo/history'
      preLoaderRoute: typeof appNgoHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/ngo/dashboard': {
      id: '/(app)/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof appNgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/profile': {
      id: '/(app)/donor/profile'
      path: '/donor/profile'
      fullPath: '/donor/profile'
      preLoaderRoute: typeof appDonorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/history': {
      id: '/(app)/donor/history'
      path: '/donor/history'
      fullPath: '/donor/history'
      preLoaderRoute: typeof appDonorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/dashboard': {
      id: '/(app)/donor/dashboard'
      path: '/donor/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof appDonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donations/$id': {
      id: '/(app)/donations/$id'
      path: '/donations/$id'
      fullPath: '/donations/$id'
      preLoaderRoute: typeof appDonationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/donations/': {
      id: '/(app)/donor/donations/'
      path: '/donor/donations'
      fullPath: '/donor/donations/'
      preLoaderRoute: typeof appDonorDonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/ngo/donations/browse': {
      id: '/(app)/ngo/donations/browse'
      path: '/ngo/donations/browse'
      fullPath: '/ngo/donations/browse'
      preLoaderRoute: typeof appNgoDonationsBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/ngo/donations/accepted': {
      id: '/(app)/ngo/donations/accepted'
      path: '/ngo/donations/accepted'
      fullPath: '/ngo/donations/accepted'
      preLoaderRoute: typeof appNgoDonationsAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/donations/create': {
      id: '/(app)/donor/donations/create'
      path: '/donor/donations/create'
      fullPath: '/donor/donations/create'
      preLoaderRoute: typeof appDonorDonationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/donor/donations/$donationId/edit': {
      id: '/(app)/donor/donations/$donationId/edit'
      path: '/donor/donations/$donationId/edit'
      fullPath: '/donor/donations/$donationId/edit'
      preLoaderRoute: typeof appDonorDonationsDonationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  appLayoutRoute: appLayoutRoute,
  appAboutRoute: appAboutRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  appDonationsIdRoute: appDonationsIdRoute,
  appDonorDashboardRoute: appDonorDashboardRoute,
  appDonorHistoryRoute: appDonorHistoryRoute,
  appDonorProfileRoute: appDonorProfileRoute,
  appNgoDashboardRoute: appNgoDashboardRoute,
  appNgoHistoryRoute: appNgoHistoryRoute,
  appNgoProfileRoute: appNgoProfileRoute,
  appDonorDonationsCreateRoute: appDonorDonationsCreateRoute,
  appNgoDonationsAcceptedRoute: appNgoDonationsAcceptedRoute,
  appNgoDonationsBrowseRoute: appNgoDonationsBrowseRoute,
  appDonorDonationsIndexRoute: appDonorDonationsIndexRoute,
  appDonorDonationsDonationIdEditRoute: appDonorDonationsDonationIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
